### ISSUE TITLE
async call request

### ISSUE THREAD

**Issue by wonderflow** [clux/kube-rs#77] opened 2019-10-14 08:13 UTC
I am trying to create a server wrapping Kubernetes api.

So when a user request my API, I need to make a request to K8s and send him the result.

But I get an Error(BlockingClientInFutureContext), after some troubleshoots.

I think it's because the lib doesn't use async reqwest client.  https://www.reddit.com/r/rust/comments/cjc9k4/reqwest_and_hyper_blockingclientinfuturecontext/evccsuh/?context=8&depth=9

 Is there any plan to return future ?

**Comment by clux** [comment] 2019-10-14 08:20
Yes. We plan on using the async reqwest client and change to async signatures soon. Duplicate of #63

**Closed by clux** 2019-10-14 08:20 UTC
