### ISSUE TITLE
List at KUBECONFIG is not properly supported

### ISSUE THREAD

**Issue by MOZGIII** [clux/kube-rs#198] opened 2020-03-26 19:34 UTC
Here's a sample `KUBECONFIG` in a list form:

```
/home/user/.kube/config:/home/user/.kube/config.d/a::/home/user/.kube/config.d/b
```

It's expected to be loaded as a single merged object.

Instead, `kube` it fails to load it with `failed to load kubeconfig: Error { inner: Os { code: 2, kind: NotFound, message: "No such file or directory" }`

**Comment by teozkr** [comment] 2020-03-26 20:04
Closing this as a duplicate of #132. That issue also contains a workaround (annoying as it is.. :/).

**Closed by teozkr** 2020-03-26 20:04 UTC
Labels: duplicate

**Comment by MOZGIII** [comment] 2020-03-26 20:15
Sorry, I couldn't find that one :+1:
